#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:8001}"
BASELINE="${BASELINE:-reports/baseline_canary_10pct.json}"
HEALTH_RETRIES="${HEALTH_RETRIES:-12}"
HEALTH_SLEEP_SEC="${HEALTH_SLEEP_SEC:-5}"

FAST_LIMIT="${FAST_LIMIT:-12}"
FULL_LIMIT="${FULL_LIMIT:-40}"
FAST_OUTPUT_PREFIX="${FAST_OUTPUT_PREFIX:-qball_week3_fast_gate}"
FULL_OUTPUT_PREFIX="${FULL_OUTPUT_PREFIX:-qball_week3_full_gate}"
FAST_GATE_OVERALL_DROP_PCT="${FAST_GATE_OVERALL_DROP_PCT:-100}"
FAST_GATE_CITATION_DROP_PCT="${FAST_GATE_CITATION_DROP_PCT:-100}"
FAST_GATE_P95_INCREASE_PCT="${FAST_GATE_P95_INCREASE_PCT:-1000}"
FAST_GATE_PROTECTED_CATEGORIES="${FAST_GATE_PROTECTED_CATEGORIES:-__fast_subset__}"
FAST_PROD_MIN_ANSWER_HIT_RATE="${FAST_PROD_MIN_ANSWER_HIT_RATE:-0}"
FAST_PROD_MIN_RETRIEVAL_HIT_RATE="${FAST_PROD_MIN_RETRIEVAL_HIT_RATE:-0}"
FAST_PROD_MIN_CITATION_VALIDITY_RATE="${FAST_PROD_MIN_CITATION_VALIDITY_RATE:-0}"
FAST_PROD_MIN_CITATION_PRECISION="${FAST_PROD_MIN_CITATION_PRECISION:-0}"
FAST_PROD_MIN_CITATION_RECALL="${FAST_PROD_MIN_CITATION_RECALL:-0}"
FAST_PROD_MAX_HALLUCINATION_RATE="${FAST_PROD_MAX_HALLUCINATION_RATE:-1}"
FAST_PROD_MIN_MUST_NOT_CONTAIN_PASS_RATE="${FAST_PROD_MIN_MUST_NOT_CONTAIN_PASS_RATE:-0}"
FAST_PROD_MAX_P95_LATENCY_MS="${FAST_PROD_MAX_P95_LATENCY_MS:-999999}"
FAST_PROD_DOMAIN_MAX_P95_LATENCY_MS="${FAST_PROD_DOMAIN_MAX_P95_LATENCY_MS:-announcements=999999,regulations=999999,curriculum=999999,multi=999999}"

echo "[week3-ci] preflight /health check against ${BASE_URL}"
ok=0
for i in $(seq 1 "${HEALTH_RETRIES}"); do
  if curl -fsS "${BASE_URL}/health" >/dev/null; then
    ok=1
    break
  fi
  echo "[week3-ci] waiting for health endpoint (${i}/${HEALTH_RETRIES})"
  sleep "${HEALTH_SLEEP_SEC}"
done

if [[ "${ok}" -ne 1 ]]; then
  echo "[week3-ci] health check failed; skipping expensive eval steps"
  echo "CI_ROLLOUT_DECISION=hold"
  exit 2
fi

echo "[week3-ci] fast gate (limit=${FAST_LIMIT})"
BASE_URL="${BASE_URL}" LIMIT="${FAST_LIMIT}" OUTPUT_PREFIX="${FAST_OUTPUT_PREFIX}" BASELINE="${BASELINE}" \
  GATE_OVERALL_DROP_PCT="${FAST_GATE_OVERALL_DROP_PCT}" \
  GATE_CITATION_DROP_PCT="${FAST_GATE_CITATION_DROP_PCT}" \
  GATE_P95_INCREASE_PCT="${FAST_GATE_P95_INCREASE_PCT}" \
  GATE_PROTECTED_CATEGORIES="${FAST_GATE_PROTECTED_CATEGORIES}" \
  PROD_MIN_ANSWER_HIT_RATE="${FAST_PROD_MIN_ANSWER_HIT_RATE}" \
  PROD_MIN_RETRIEVAL_HIT_RATE="${FAST_PROD_MIN_RETRIEVAL_HIT_RATE}" \
  PROD_MIN_CITATION_VALIDITY_RATE="${FAST_PROD_MIN_CITATION_VALIDITY_RATE}" \
  PROD_MIN_CITATION_PRECISION="${FAST_PROD_MIN_CITATION_PRECISION}" \
  PROD_MIN_CITATION_RECALL="${FAST_PROD_MIN_CITATION_RECALL}" \
  PROD_MAX_HALLUCINATION_RATE="${FAST_PROD_MAX_HALLUCINATION_RATE}" \
  PROD_MIN_MUST_NOT_CONTAIN_PASS_RATE="${FAST_PROD_MIN_MUST_NOT_CONTAIN_PASS_RATE}" \
  PROD_MAX_P95_LATENCY_MS="${FAST_PROD_MAX_P95_LATENCY_MS}" \
  PROD_DOMAIN_MAX_P95_LATENCY_MS="${FAST_PROD_DOMAIN_MAX_P95_LATENCY_MS}" \
  bash scripts/run_canary_guard.sh

echo "[week3-ci] full gate (limit=${FULL_LIMIT})"
BASE_URL="${BASE_URL}" LIMIT="${FULL_LIMIT}" OUTPUT_PREFIX="${FULL_OUTPUT_PREFIX}" BASELINE="${BASELINE}" \
  bash scripts/run_canary_guard.sh

echo "[week3-ci] metric sanity check on full gate report"
python3 scripts/check_eval_metric_sanity.py --report-json "${FULL_OUTPUT_PREFIX}.json"

echo "[week3-ci] ranking robustness check on full gate report"
python3 scripts/check_ranking_robustness.py --report-json "${FULL_OUTPUT_PREFIX}.json"

echo "[week3-ci] completed"
